require("./components/hero").hero();
require("./components/hero").pixel_hero();
require("./components/test").hero_images();
require("./components/service").service_scroll();
require("./components/service").service_headline();
require("./components/d-animation").d_animation();
require("./reusables/blogCard").blogCard();
require("./components/project_card").project_card();
require("./components/added_numbers").added_numbers();
